displayName: Secure Link
type: middleware

import: github.com/trois-six/plugin-securelink

compatibility: TODO

summary: Checks authenticity of requested links, protect resources from unauthorized access.

iconPath: assets/icon.png
bannerPath: assets/banner.png

testData:
  secret: enigma
  protectedPaths:
    - "/video/"
    - "/playlist"
